def get_final_list(dc):
  system_info = {}
  system_info['ams2'] = { 'firmware_version': 'N/A',
  'fqdn': 'adc0001.davidmonarrez.com',
  'hostname': u'adc0001.local',
  'last_config_saved': '04:55 PM Wed Aug 12 2015',
  'service_groups': [ { 'ip_address': '8.10.225.44',
                        'name': 'vip_auction1_prod',
                        'servers': { '443': { '10.10.118.74': { 'port': '8080',
                                                                'server_hostname': 'drpp-bea0001.ams2.davidmonarrez.com',
                                                                'server_status': '1'},
                                              '10.10.118.75': { 'port': '8080',
                                                                'server_hostname': 'drpp-bea0000.ams2.davidmonarrez.com',
                                                                'server_status': '1'},
                                              '10.10.41.50': { 'port': '8080',
                                                               'server_hostname': 'drpp-bea1000.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                              '10.10.41.51': { 'port': '8080',
                                                               'server_hostname': 'drpp-bea1001.ams2.davidmonarrez.com',
                                                               'server_status': '1'}},
                                     '80': { '10.10.118.74': { 'port': '8080',
                                                               'server_hostname': 'drpp-bea0001.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                             '10.10.118.75': { 'port': '8080',
                                                               'server_hostname': 'drpp-bea0000.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                             '10.10.41.50': { 'port': '8080',
                                                              'server_hostname': 'drpp-bea1000.ams2.davidmonarrez.com',
                                                              'server_status': '1'},
                                             '10.10.41.51': { 'port': '8080',
                                                              'server_hostname': 'drpp-bea1001.ams2.davidmonarrez.com',
                                                              'server_status': '1'}}},
                        'status': '1'},
                      { 'ip_address': '8.10.225.26',
                        'name': 'vip_auction2_prod',
                        'servers': { '443': { '10.10.118.76': { 'port': '8080',
                                                                'server_hostname': 'drpp-bea0002.ams2.davidmonarrez.com',
                                                                'server_status': '1'},
                                              '10.10.118.77': { 'port': '8080',
                                                                'server_hostname': 'drpp-bea0003.ams2.davidmonarrez.com',
                                                                'server_status': '1'},
                                              '10.10.118.81': { 'port': '8080',
                                                                'server_hostname': 'drpp-bea0004.ams2.davidmonarrez.com',
                                                                'server_status': '1'},
                                              '10.10.41.52': { 'port': '8080',
                                                               'server_hostname': 'drpp-bea1002.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                              '10.10.41.53': { 'port': '8080',
                                                               'server_hostname': 'drpp-bea1003.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                              '10.10.41.57': { 'port': '8080',
                                                               'server_hostname': 'drpp-bea1004.ams2.davidmonarrez.com',
                                                               'server_status': '1'}},
                                     '80': { '10.10.118.76': { 'port': '8080',
                                                               'server_hostname': 'drpp-bea0002.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                             '10.10.118.77': { 'port': '8080',
                                                               'server_hostname': 'drpp-bea0003.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                             '10.10.118.81': { 'port': '8080',
                                                               'server_hostname': 'drpp-bea0004.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                             '10.10.41.52': { 'port': '8080',
                                                              'server_hostname': 'drpp-bea1002.ams2.davidmonarrez.com',
                                                              'server_status': '1'},
                                             '10.10.41.53': { 'port': '8080',
                                                              'server_hostname': 'drpp-bea1003.ams2.davidmonarrez.com',
                                                              'server_status': '1'},
                                             '10.10.41.57': { 'port': '8080',
                                                              'server_hostname': 'drpp-bea1004.ams2.davidmonarrez.com',
                                                              'server_status': '1'}}},
                        'status': '1'},
                      { 'ip_address': '8.10.225.40',
                        'name': 'vip_bidder1_prod',
                        'servers': { '443': { '10.10.118.100': { 'port': '8080',
                                                                 'server_hostname': 'drps-bcb0018.ams2.davidmonarrez.com',
                                                                 'server_status': '2'},
                                              '10.10.118.82': { 'port': '8080',
                                                                'server_hostname': 'drpp-bcb0000.ams2.davidmonarrez.com',
                                                                'server_status': '1'},
                                              '10.10.118.83': { 'port': '8080',
                                                                'server_hostname': 'drpp-bcb0001.ams2.davidmonarrez.com',
                                                                'server_status': '1'},
                                              '10.10.118.84': { 'port': '8080',
                                                                'server_hostname': 'drpp-bcb0002.ams2.davidmonarrez.com',
                                                                'server_status': '1'},
                                              '10.10.118.85': { 'port': '8080',
                                                                'server_hostname': 'drpp-bcb0003.ams2.davidmonarrez.com',
                                                                'server_status': '1'},
                                              '10.10.118.86': { 'port': '8080',
                                                                'server_hostname': 'drpp-bcb0004.ams2.davidmonarrez.com',
                                                                'server_status': '1'},
                                              '10.10.118.87': { 'port': '8080',
                                                                'server_hostname': 'drpp-bcb0005.ams2.davidmonarrez.com',
                                                                'server_status': '1'},
                                              '10.10.118.88': { 'port': '8080',
                                                                'server_hostname': 'drpp-bcb0006.ams2.davidmonarrez.com',
                                                                'server_status': '1'},
                                              '10.10.118.89': { 'port': '8080',
                                                                'server_hostname': 'drpp-bcb0007.ams2.davidmonarrez.com',
                                                                'server_status': '1'},
                                              '10.10.118.90': { 'port': '8080',
                                                                'server_hostname': 'drpp-bcb0008.ams2.davidmonarrez.com',
                                                                'server_status': '1'},
                                              '10.10.118.91': { 'port': '8080',
                                                                'server_hostname': 'drpp-bcb0009.ams2.davidmonarrez.com',
                                                                'server_status': '1'},
                                              '10.10.118.92': { 'port': '8080',
                                                                'server_hostname': 'drpp-bcb0010.ams2.davidmonarrez.com',
                                                                'server_status': '1'},
                                              '10.10.118.93': { 'port': '8080',
                                                                'server_hostname': 'drpp-bcb0011.ams2.davidmonarrez.com',
                                                                'server_status': '1'},
                                              '10.10.118.94': { 'port': '8080',
                                                                'server_hostname': 'drpp-bcb0012.ams2.davidmonarrez.com',
                                                                'server_status': '1'},
                                              '10.10.118.95': { 'port': '8080',
                                                                'server_hostname': 'drpp-bcb0013.ams2.davidmonarrez.com',
                                                                'server_status': '1'},
                                              '10.10.118.96': { 'port': '8080',
                                                                'server_hostname': 'drpp-bcb0014.ams2.davidmonarrez.com',
                                                                'server_status': '1'},
                                              '10.10.118.97': { 'port': '8080',
                                                                'server_hostname': 'drpp-bcb0015.ams2.davidmonarrez.com',
                                                                'server_status': '1'},
                                              '10.10.118.98': { 'port': '8080',
                                                                'server_hostname': 'drps-bcb0016.ams2.davidmonarrez.com',
                                                                'server_status': '2'},
                                              '10.10.118.99': { 'port': '8080',
                                                                'server_hostname': 'drps-bcb0017.ams2.davidmonarrez.com',
                                                                'server_status': '2'},
                                              '10.10.41.41': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb1017.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                              '10.10.41.42': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb1018.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                              '10.10.41.58': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb1000.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                              '10.10.41.59': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb1001.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                              '10.10.41.60': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb1002.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                              '10.10.41.61': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb1003.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                              '10.10.41.62': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb1004.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                              '10.10.41.63': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb1005.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                              '10.10.41.64': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb1006.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                              '10.10.41.65': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb1007.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                              '10.10.41.66': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb1008.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                              '10.10.41.67': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb1009.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                              '10.10.41.68': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb1010.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                              '10.10.41.69': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb1011.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                              '10.10.41.70': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb1012.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                              '10.10.41.71': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb1013.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                              '10.10.41.72': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb1014.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                              '10.10.41.73': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb1015.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                              '10.10.41.74': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb1016.ams2.davidmonarrez.com',
                                                               'server_status': '1'}},
                                     '80': { '10.10.118.100': { 'port': '8080',
                                                                'server_hostname': 'drps-bcb0018.ams2.davidmonarrez.com',
                                                                'server_status': '2'},
                                             '10.10.118.82': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb0000.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                             '10.10.118.83': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb0001.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                             '10.10.118.84': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb0002.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                             '10.10.118.85': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb0003.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                             '10.10.118.86': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb0004.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                             '10.10.118.87': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb0005.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                             '10.10.118.88': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb0006.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                             '10.10.118.89': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb0007.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                             '10.10.118.90': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb0008.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                             '10.10.118.91': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb0009.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                             '10.10.118.92': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb0010.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                             '10.10.118.93': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb0011.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                             '10.10.118.94': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb0012.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                             '10.10.118.95': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb0013.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                             '10.10.118.96': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb0014.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                             '10.10.118.97': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb0015.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                             '10.10.118.98': { 'port': '8080',
                                                               'server_hostname': 'drps-bcb0016.ams2.davidmonarrez.com',
                                                               'server_status': '2'},
                                             '10.10.118.99': { 'port': '8080',
                                                               'server_hostname': 'drps-bcb0017.ams2.davidmonarrez.com',
                                                               'server_status': '2'},
                                             '10.10.41.41': { 'port': '8080',
                                                              'server_hostname': 'drpp-bcb1017.ams2.davidmonarrez.com',
                                                              'server_status': '1'},
                                             '10.10.41.42': { 'port': '8080',
                                                              'server_hostname': 'drpp-bcb1018.ams2.davidmonarrez.com',
                                                              'server_status': '1'},
                                             '10.10.41.58': { 'port': '8080',
                                                              'server_hostname': 'drpp-bcb1000.ams2.davidmonarrez.com',
                                                              'server_status': '1'},
                                             '10.10.41.59': { 'port': '8080',
                                                              'server_hostname': 'drpp-bcb1001.ams2.davidmonarrez.com',
                                                              'server_status': '1'},
                                             '10.10.41.60': { 'port': '8080',
                                                              'server_hostname': 'drpp-bcb1002.ams2.davidmonarrez.com',
                                                              'server_status': '1'},
                                             '10.10.41.61': { 'port': '8080',
                                                              'server_hostname': 'drpp-bcb1003.ams2.davidmonarrez.com',
                                                              'server_status': '1'},
                                             '10.10.41.62': { 'port': '8080',
                                                              'server_hostname': 'drpp-bcb1004.ams2.davidmonarrez.com',
                                                              'server_status': '1'},
                                             '10.10.41.63': { 'port': '8080',
                                                              'server_hostname': 'drpp-bcb1005.ams2.davidmonarrez.com',
                                                              'server_status': '1'},
                                             '10.10.41.64': { 'port': '8080',
                                                              'server_hostname': 'drpp-bcb1006.ams2.davidmonarrez.com',
                                                              'server_status': '1'},
                                             '10.10.41.65': { 'port': '8080',
                                                              'server_hostname': 'drpp-bcb1007.ams2.davidmonarrez.com',
                                                              'server_status': '1'},
                                             '10.10.41.66': { 'port': '8080',
                                                              'server_hostname': 'drpp-bcb1008.ams2.davidmonarrez.com',
                                                              'server_status': '1'},
                                             '10.10.41.67': { 'port': '8080',
                                                              'server_hostname': 'drpp-bcb1009.ams2.davidmonarrez.com',
                                                              'server_status': '1'},
                                             '10.10.41.68': { 'port': '8080',
                                                              'server_hostname': 'drpp-bcb1010.ams2.davidmonarrez.com',
                                                              'server_status': '1'},
                                             '10.10.41.69': { 'port': '8080',
                                                              'server_hostname': 'drpp-bcb1011.ams2.davidmonarrez.com',
                                                              'server_status': '1'},
                                             '10.10.41.70': { 'port': '8080',
                                                              'server_hostname': 'drpp-bcb1012.ams2.davidmonarrez.com',
                                                              'server_status': '1'},
                                             '10.10.41.71': { 'port': '8080',
                                                              'server_hostname': 'drpp-bcb1013.ams2.davidmonarrez.com',
                                                              'server_status': '1'},
                                             '10.10.41.72': { 'port': '8080',
                                                              'server_hostname': 'drpp-bcb1014.ams2.davidmonarrez.com',
                                                              'server_status': '1'},
                                             '10.10.41.73': { 'port': '8080',
                                                              'server_hostname': 'drpp-bcb1015.ams2.davidmonarrez.com',
                                                              'server_status': '1'},
                                             '10.10.41.74': { 'port': '8080',
                                                              'server_hostname': 'drpp-bcb1016.ams2.davidmonarrez.com',
                                                              'server_status': '1'}}},
                        'status': '1'},
                      { 'ip_address': '10.10.4.65',
                        'name': 'vip_bidder2_prod',
                        'servers': { '443': { '10.10.118.78': { 'port': '8080',
                                                                'server_hostname': 'drpp-bcg0000.ams2.davidmonarrez.com',
                                                                'server_status': '1'},
                                              '10.10.118.79': { 'port': '8080',
                                                                'server_hostname': 'drpp-bcg0001.ams2.davidmonarrez.com',
                                                                'server_status': '1'},
                                              '10.10.118.80': { 'port': '8080',
                                                                'server_hostname': 'drpp-bcg0002.ams2.davidmonarrez.com',
                                                                'server_status': '1'},
                                              '10.10.41.54': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcg1000.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                              '10.10.41.55': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcg1001.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                              '10.10.41.56': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcg1002.ams2.davidmonarrez.com',
                                                               'server_status': '1'}},
                                     '80': { '10.10.118.78': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcg0000.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                             '10.10.118.79': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcg0001.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                             '10.10.118.80': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcg0002.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                             '10.10.41.54': { 'port': '8080',
                                                              'server_hostname': 'drpp-bcg1000.ams2.davidmonarrez.com',
                                                              'server_status': '1'},
                                             '10.10.41.55': { 'port': '8080',
                                                              'server_hostname': 'drpp-bcg1001.ams2.davidmonarrez.com',
                                                              'server_status': '1'},
                                             '10.10.41.56': { 'port': '8080',
                                                              'server_hostname': 'drpp-bcg1002.ams2.davidmonarrez.com',
                                                              'server_status': '1'}}},
                        'status': '1'},
                      { 'ip_address': '10.10.4.64',
                        'name': 'vip_bidder3_prod',
                        'servers': { '443': { '10.10.118.100': { 'port': '8080',
                                                                 'server_hostname': 'drps-bcb0018.ams2.davidmonarrez.com',
                                                                 'server_status': '2'},
                                              '10.10.118.82': { 'port': '8080',
                                                                'server_hostname': 'drpp-bcb0000.ams2.davidmonarrez.com',
                                                                'server_status': '1'},
                                              '10.10.118.83': { 'port': '8080',
                                                                'server_hostname': 'drpp-bcb0001.ams2.davidmonarrez.com',
                                                                'server_status': '1'},
                                              '10.10.118.84': { 'port': '8080',
                                                                'server_hostname': 'drpp-bcb0002.ams2.davidmonarrez.com',
                                                                'server_status': '1'},
                                              '10.10.118.85': { 'port': '8080',
                                                                'server_hostname': 'drpp-bcb0003.ams2.davidmonarrez.com',
                                                                'server_status': '1'},
                                              '10.10.118.86': { 'port': '8080',
                                                                'server_hostname': 'drpp-bcb0004.ams2.davidmonarrez.com',
                                                                'server_status': '1'},
                                              '10.10.118.87': { 'port': '8080',
                                                                'server_hostname': 'drpp-bcb0005.ams2.davidmonarrez.com',
                                                                'server_status': '1'},
                                              '10.10.118.88': { 'port': '8080',
                                                                'server_hostname': 'drpp-bcb0006.ams2.davidmonarrez.com',
                                                                'server_status': '1'},
                                              '10.10.118.89': { 'port': '8080',
                                                                'server_hostname': 'drpp-bcb0007.ams2.davidmonarrez.com',
                                                                'server_status': '1'},
                                              '10.10.118.90': { 'port': '8080',
                                                                'server_hostname': 'drpp-bcb0008.ams2.davidmonarrez.com',
                                                                'server_status': '1'},
                                              '10.10.118.91': { 'port': '8080',
                                                                'server_hostname': 'drpp-bcb0009.ams2.davidmonarrez.com',
                                                                'server_status': '1'},
                                              '10.10.118.92': { 'port': '8080',
                                                                'server_hostname': 'drpp-bcb0010.ams2.davidmonarrez.com',
                                                                'server_status': '1'},
                                              '10.10.118.93': { 'port': '8080',
                                                                'server_hostname': 'drpp-bcb0011.ams2.davidmonarrez.com',
                                                                'server_status': '1'},
                                              '10.10.118.94': { 'port': '8080',
                                                                'server_hostname': 'drpp-bcb0012.ams2.davidmonarrez.com',
                                                                'server_status': '1'},
                                              '10.10.118.95': { 'port': '8080',
                                                                'server_hostname': 'drpp-bcb0013.ams2.davidmonarrez.com',
                                                                'server_status': '1'},
                                              '10.10.118.96': { 'port': '8080',
                                                                'server_hostname': 'drpp-bcb0014.ams2.davidmonarrez.com',
                                                                'server_status': '1'},
                                              '10.10.118.97': { 'port': '8080',
                                                                'server_hostname': 'drpp-bcb0015.ams2.davidmonarrez.com',
                                                                'server_status': '1'},
                                              '10.10.118.98': { 'port': '8080',
                                                                'server_hostname': 'drps-bcb0016.ams2.davidmonarrez.com',
                                                                'server_status': '2'},
                                              '10.10.118.99': { 'port': '8080',
                                                                'server_hostname': 'drps-bcb0017.ams2.davidmonarrez.com',
                                                                'server_status': '2'},
                                              '10.10.41.41': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb1017.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                              '10.10.41.42': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb1018.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                              '10.10.41.58': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb1000.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                              '10.10.41.59': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb1001.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                              '10.10.41.60': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb1002.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                              '10.10.41.61': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb1003.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                              '10.10.41.62': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb1004.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                              '10.10.41.63': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb1005.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                              '10.10.41.64': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb1006.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                              '10.10.41.65': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb1007.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                              '10.10.41.66': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb1008.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                              '10.10.41.67': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb1009.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                              '10.10.41.68': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb1010.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                              '10.10.41.69': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb1011.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                              '10.10.41.70': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb1012.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                              '10.10.41.71': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb1013.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                              '10.10.41.72': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb1014.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                              '10.10.41.73': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb1015.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                              '10.10.41.74': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb1016.ams2.davidmonarrez.com',
                                                               'server_status': '1'}},
                                     '80': { '10.10.118.100': { 'port': '8080',
                                                                'server_hostname': 'drps-bcb0018.ams2.davidmonarrez.com',
                                                                'server_status': '2'},
                                             '10.10.118.82': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb0000.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                             '10.10.118.83': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb0001.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                             '10.10.118.84': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb0002.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                             '10.10.118.85': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb0003.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                             '10.10.118.86': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb0004.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                             '10.10.118.87': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb0005.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                             '10.10.118.88': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb0006.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                             '10.10.118.89': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb0007.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                             '10.10.118.90': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb0008.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                             '10.10.118.91': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb0009.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                             '10.10.118.92': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb0010.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                             '10.10.118.93': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb0011.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                             '10.10.118.94': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb0012.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                             '10.10.118.95': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb0013.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                             '10.10.118.96': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb0014.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                             '10.10.118.97': { 'port': '8080',
                                                               'server_hostname': 'drpp-bcb0015.ams2.davidmonarrez.com',
                                                               'server_status': '1'},
                                             '10.10.118.98': { 'port': '8080',
                                                               'server_hostname': 'drps-bcb0016.ams2.davidmonarrez.com',
                                                               'server_status': '2'},
                                             '10.10.118.99': { 'port': '8080',
                                                               'server_hostname': 'drps-bcb0017.ams2.davidmonarrez.com',
                                                               'server_status': '2'},
                                             '10.10.41.41': { 'port': '8080',
                                                              'server_hostname': 'drpp-bcb1017.ams2.davidmonarrez.com',
                                                              'server_status': '1'},
                                             '10.10.41.42': { 'port': '8080',
                                                              'server_hostname': 'drpp-bcb1018.ams2.davidmonarrez.com',
                                                              'server_status': '1'},
                                             '10.10.41.58': { 'port': '8080',
                                                              'server_hostname': 'drpp-bcb1000.ams2.davidmonarrez.com',
                                                              'server_status': '1'},
                                             '10.10.41.59': { 'port': '8080',
                                                              'server_hostname': 'drpp-bcb1001.ams2.davidmonarrez.com',
                                                              'server_status': '1'},
                                             '10.10.41.60': { 'port': '8080',
                                                              'server_hostname': 'drpp-bcb1002.ams2.davidmonarrez.com',
                                                              'server_status': '1'},
                                             '10.10.41.61': { 'port': '8080',
                                                              'server_hostname': 'drpp-bcb1003.ams2.davidmonarrez.com',
                                                              'server_status': '1'},
                                             '10.10.41.62': { 'port': '8080',
                                                              'server_hostname': 'drpp-bcb1004.ams2.davidmonarrez.com',
                                                              'server_status': '1'},
                                             '10.10.41.63': { 'port': '8080',
                                                              'server_hostname': 'drpp-bcb1005.ams2.davidmonarrez.com',
                                                              'server_status': '1'},
                                             '10.10.41.64': { 'port': '8080',
                                                              'server_hostname': 'drpp-bcb1006.ams2.davidmonarrez.com',
                                                              'server_status': '1'},
                                             '10.10.41.65': { 'port': '8080',
                                                              'server_hostname': 'drpp-bcb1007.ams2.davidmonarrez.com',
                                                              'server_status': '1'},
                                             '10.10.41.66': { 'port': '8080',
                                                              'server_hostname': 'drpp-bcb1008.ams2.davidmonarrez.com',
                                                              'server_status': '1'},
                                             '10.10.41.67': { 'port': '8080',
                                                              'server_hostname': 'drpp-bcb1009.ams2.davidmonarrez.com',
                                                              'server_status': '1'},
                                             '10.10.41.68': { 'port': '8080',
                                                              'server_hostname': 'drpp-bcb1010.ams2.davidmonarrez.com',
                                                              'server_status': '1'},
                                             '10.10.41.69': { 'port': '8080',
                                                              'server_hostname': 'drpp-bcb1011.ams2.davidmonarrez.com',
                                                              'server_status': '1'},
                                             '10.10.41.70': { 'port': '8080',
                                                              'server_hostname': 'drpp-bcb1012.ams2.davidmonarrez.com',
                                                              'server_status': '1'},
                                             '10.10.41.71': { 'port': '8080',
                                                              'server_hostname': 'drpp-bcb1013.ams2.davidmonarrez.com',
                                                              'server_status': '1'},
                                             '10.10.41.72': { 'port': '8080',
                                                              'server_hostname': 'drpp-bcb1014.ams2.davidmonarrez.com',
                                                              'server_status': '1'},
                                             '10.10.41.73': { 'port': '8080',
                                                              'server_hostname': 'drpp-bcb1015.ams2.davidmonarrez.com',
                                                              'server_status': '1'},
                                             '10.10.41.74': { 'port': '8080',
                                                              'server_hostname': 'drpp-bcb1016.ams2.davidmonarrez.com',
                                                              'server_status': '1'}}},
                        'status': '1'}],
  'software_version': '2.0.1-P1(build: 60)'}

  #return lb_info
  
  return system_info['ams2']
